apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Ressourcen, die verwaltet werden sollen
resources:
  - backend-redis-secret.yaml
  - system-redis-secret.yaml
  - system-database-secret.yaml
  - api-manager.yaml

# 2. Gemeinsame Metadaten f√ºr alle Ressourcen
namespace: 3scale