apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey-config
  labels:
    app: valkey
  annotations:
    argocd.argoproj.io/sync-wave: "00"
data:
  valkey.conf: |
    # Minimal example config. Tweak as needed.
    bind 0.0.0.0
    port 6379
    protected-mode no

    # Persistence (AOF) - uncomment if you want AOF.
    # appendonly yes
    # appendfilename "appendonly.aof"

    # Snapshotting (RDB) example:
    save 900 1
    save 300 10
    save 60 10000

    # Location for persistence files
    dir /var/lib/valkey